stages:
  - deploy

deploy_to_github:
  stage: deploy
  rules:
    - changes:
        - frontend/src/contracts/contract-address.json
        - frontend/src/contracts/Token.json
        - frontend/src/contracts/MyNFT.json
        - frontend/src/contracts/NFTMarket.json
      when: always
    - when: never
  script:
    - echo "Adding GitHub remote..."
    - git remote add github "${GITHUB_REPO_URL}" || echo "Remote already exists"
    - echo "Pushing changes to GitHub..."
    - git push github HEAD:main
  only:
    - branches
  variables:
    GITHUB_REPO_URL: "https://AlainCognito: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@github.com/AlainCognito/blockchain-project-live.git"
