stages:
  - update

update_artifacts:
  stage: update
  script:
    - echo "Checking for artifact changes..."
    - |
      CHANGED_FILES=$(git status --porcelain frontend/src/contracts/contract-address.json frontend/src/contracts/Token.json frontend/src/contracts/MyNFT.json frontend/src/contracts/NFTMarket.json)
      if [ -n "$CHANGED_FILES" ]; then
        echo "Artifact changes detected, committing and pushing to master..."
        # Configure git if needed
        git config --global user.email "ci@example.com"
        git config --global user.name "GitLab CI"
        git add frontend/src/contracts/contract-address.json frontend/src/contracts/Token.json frontend/src/contracts/MyNFT.json frontend/src/contracts/NFTMarket.json
        git commit -m "chore: update deployed contract addresses"
        git push github master
        echo "Commit and push complete."
      else
        echo "No changes in contract artifacts. Nothing to commit."
      fi