services:
  hardhat-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: hardhat-node
    restart: unless-stopped

  ngrok:
    image: wernight/ngrok:latest
    depends_on:
      - hardhat-node
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=2uV8OqsEINccaMNZUuY7a96OYlc_4Rd25zt148tYJY7zadL53
    command: ngrok http hardhat-node:8545
    restart: unless-stopped

  deployer:
    build:
      context: .
      dockerfile: Dockerfile
      target: hardhat-node
    depends_on:
      hardhat-node:
    command: >
      sh -c "until nc -z hardhat-node 8545; do echo 'Waiting for hardhat node...'; sleep 2; done;
      cd app && npx hardhat run scripts/deploy.js --network localhost"
