services:
  hardhat-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: hardhat-node
    volumes:
      - ./frontend/src/contracts:/app/frontend/src/contracts
    restart: unless-stopped

  ngrok:
    depends_on:
      - hardhat-node
    ports:
      - "4040:4040"
    build: 
      dockerfile: Dockerfile
      target: ngrok
    volumes:
      - ./frontend/src/contracts:/frontend/src/contracts
      - ./bin:/frontend/bin
    environment:
      - NGROK_AUTHTOKEN=2uV8OqsEINccaMNZUuY7a96OYlc_4Rd25zt148tYJY7zadL53
    command: ngrok http hardhat-node:8545
    restart: unless-stopped