services:
  hardhat-node:
    build:
      context: .
      dockerfile: Dockerfile
      target: hardhat-node
      network: host
    volumes:
      - ./frontend/src/contracts:/frontend/src/contracts
      - ./frontend/public/metadata:/frontend/public/metadata
      - ./app:/app
    restart: unless-stopped
    

  ngrok:
    depends_on:
      - hardhat-node
    ports:
      - "4040:4040"
    build:
      dockerfile: Dockerfile
      target: ngrok
      network: host
    volumes:
      - ./frontend/src/contracts:/frontend/src/contracts
      - ./bin:/frontend/bin
    environment:
      - NGROK_AUTHTOKEN=2uV8OqsEINccaMNZUuY7a96OYlc_4Rd25zt148tYJY7zadL53
    command: ngrok http hardhat-node:8545
    restart: unless-stopped

  # ipfs:
  #   container_name: ipfs_host
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: ipfs
  #   volumes:
  #     - ${ipfs_staging}:/export
  #     - ${ipfs_data}:/data/ipfs
  #   ports:
  #     - "4001:4001"
  #     - "4001:4001/udp"
  #     - "127.0.0.1:8080:8080"
  #     - "127.0.0.1:5001:5001"
  #   restart: unless-stopped
